2015-03-29 * Debugged ProductCreate (click on "Produkt Hinzufügen") 	* BUG: Uncaught TypeError: undefined is not a function * Direct Ordering in Product View only for admin * Switching product_state only for admin * can now delete products (when no open orders found) * deleted orders and products are removed from list view. * on product create form is now cleared, form tab is opened * detail order view is hidden.
2015-03-26
* Added basic functionality to hide admin-views for non-admins in tasks, users, orders

2015-03-24
* DASHBOARD:
	* MyTasks put into CanJs: Possible view and delete myTasks
	* Upcoming Tasks put into CanJs: Possible to view and assign to Task
* Added Sort-Plugin to app.js
* Added Routing for MyTasks and Upcoming Tasks in Dashboard
* When member removes himself from task event is fired